### PR TITLE
Remove TrayIcon_OnLeftClicked since Linux also has Open option in tray menu now

### PR DESCRIPTION
**Pull request by sidevesh**

### CODE REVIEW

**Comment by nift4** [comment]
What about Windows?

**Comment by sidevesh** [comment]
Wouldn't the same thing apple to Windows too ? Unless on Windows it does not open the tray menu on left click.

I don't have any Windows machine so I can't test the change on it, will be great if someone who has Windows can.

**Comment by nift4** [comment]
Windows opens tray menus on right click and hence this would make left click a no-op, based on my understanding of Avalonia docs (and this also applies to some Linux desktops):
grafik

**Comment by sidevesh** [comment]
Updated the PR so left click is only handled on Windows

**Comment by ThePBone** [comment]
Most Linux desktop environments (such as KDE for example) also use left-clicks to open apps attached to tray icons by convention. So we shouldn't remove that event handler; otherwise, left-clicks would be unhandled.

The 'Open' option was added to the context menu as a workaround in case the tray bar of the desktop environment doesn't support left-click events or maps the left-click to the context menu.

**Pull request closed without merging**
