### PR TITLE
Add portuguese translation

### PR DESCRIPTION
**Pull request by lucasskluser**
First of all, I love this project.
Second, I added a Portuguese translation.

### CODE REVIEW

**Comment by ArthurWolfhound** [comment]
Hi! I don't know if you found that one, but I think I should let you know, that if you save your file as `custom_language.xaml` and place it right near executable (in Program Files) then when started, application will jump into translator mode so you can check if all your translations correctly fit into user interface.

I found that out when checking in with developer and since then if I need to modify my RUS/UKR translations I use that to verify everything.

Cheers!

**Comment by ArthurWolfhound** [comment]
Actually, you know, I decided to check on that one personally. And found the very same problem that I had. That one was like the most painful. Other places look fine, but I don't know Portuguese so better you check on that one than me.

image

**Comment by ThePBone** [comment]
Thanks for your contribution!
Could you please shorten the two overlapping strings on the update page? (see @ArthurWolfhound's screenshot). Something like 'Skip' instead of 'Skip this version' for example.
But otherwise, this looks good, I'll merge it as soon as you're done. :+1:

**Comment by lucasskluser** [comment]
Thanks for you feedback @ArthurWolfhound! I didn't know about `custom_language.xaml`.

@ThePBone I opened the manager with `custom_language.xaml` and made the necessary corrections.

Examples:

image
image

**Comment by ThePBone** [comment]
Thanks! 
I think I'll better document the translator mode either in a contribution.md or in the readme.

**Pull request merged**
