### PR TITLE
Update to RU and UA translations and readme files

### PR DESCRIPTION
**Pull request by ArthurWolfhound**
Hi! I am back! Again thanking you for such wonderful piece of software. Re-reading things about custom actions, I actually had an idea, though I don't know if it will be useful? Okay.

## Big challenge!

You warn users that Galaxy Wearable will reset custom actions if opened **and** that your program will require to sit in background for said actions to work, right?

Concept: Is it possible to implement something like service-based solution that will catch normally set functions from Buds, but treat them differently because Custom actions Mode is Active?

According to your current layout my concept looks like:
1. Touchpad page header
2. Lock touchpad toggle
3. Sync actions on phone and pc toggle
4. Explanation bar which will also inform why sync toggle turns off if you try to use Custom actions setting
5. Actions on PC for left and right bud, but this list will include custom actions as item to choose unlike the next one
6. Actions on Phone which will appear only if sync toggle is disabled, though you still can edit those actions, because why not

## Minor challenge 
And also if you have mood for that (though here I am being seriously petty) - connection popup only appears on main screen - what about dual screen setups? Or even more screen setups? Though I only have two.

Cheers!

### CODE REVIEW

**Comment by ThePBone** [comment]
> Concept: Is it possible to implement something like a service-based solution that will catch normally set functions from Buds, but treat them differently because Custom actions Mode is Active?

Well, receiving long-press touch events can bé a bit tricky in some cases.
For example, if the option is set to 'Ambient sound' but I'm overriding this event on the software side, I cannot prevent the device from turning ambient sound on/off. Or when set to 'Voice assistant', there's not even an easy way to detect the touch press on Windows, because it is sent over another protocol (AVRCP) to which we don't have access on this OS (unless we would write our own Bluetooth driver).
The same goes for other touch options as well, intercepting a touch event is hard, preventing the Buds from executing the touch event and detecting which side it was sent from is almost impossible.

That's why I'm making use of unused/custom action ids for these custom actions. Action ids 0x04 to 0xFF are not assigned and trigger no event visible to the user. However, unlike the standard actions, they send a small message back to the host device, which allows us to reliably detect whether an event was sent (and from which side it originated!).


About the minor issue: I'll see if I can set up a virtual second monitor to test this. It shouldn't be too hard.

**Comment by ArthurWolfhound** [comment]
Yup! Should have guessed that is quite complicated. Sorry for that weird bot destroying pull request. I've disabled it and will re-submit it now.

**Comment by ThePBone** [comment]
Sorry for this bot,

**Comment by ThePBone** [comment]
Sorry for this bot, it should have labeled any PR editing the language files as 'translation'. (Either caused by server or permission issues) I've already removed the GitHub Action that caused it yesterday, however I can still merge pull requests, even when one of the GitHub Actions fails (unless they are marked as mandatory)

**Comment by ArthurWolfhound** [comment]
Don't be sorry. You probably don't see what I mean. I have installed a pull-bot that should've synced my fork with yours if you make any changes to your repository after accepting my pull request - but instead it triggered pull from your repo to mine and erased my work.

So I got my offline copy, commited it agian and then dropped another pull request...

**Comment by ThePBone** [comment]
Update: I found a way to accomplish your *big challenge* by "reusing" the voice notification feature from the Android app.

Before the TTS engine on the phone reads the message out loud, the Android app sends an `MSG_ID_VOICE_NOTI_STATUS` request with a one-byte payload that can be either 1 or 0 (to allow users to cancel the TTS engine by tapping). This switches the Buds into another mode where all touch options are disabled and have the same effect: just beeping once and sending an `MSG_ID_VOICE_NOTI_STOP` response back. (Bypassing all default and custom actions)
However, we still don't know which side and how the touch event (single-/double-press/held down) was triggered. Luckily, the Buds also transmit an unused debug message (id 45) every time a touch event has been triggered that contains this exact missing information. Unfortunately, this debug message behaves differently for each Buds model. IIRC, the original Buds only send a two-byte payload, the Buds Plus three bytes and the Buds Live apparently ~16 bytes, but it shouldn't be too hard to filter the correct data out.

So yes, this should be possible to implement your idea. By using this method, we should even be able to remap the single-, double-, and triple-touch actions without altering the device at all.

**Comment by ArthurWolfhound** [comment]
Great to know that my suggestion is of any use!
I personally don't own a pair, but my good friend actually owns original one! So it won't be a big deal to get them for testing for a few hours. 

When I say not a big deal, I mean he's living on the 5th floor and I live on 8th floor - so yeah 😁

Drop here which settings I should set on them and how exactly I should tap on them, and you'll get packet debug info as fast as I can reach him (he's first year uni and this covid makes everything so difficult, he's offline, I am online...mweh)

Look forward to help!

**Comment by ThePBone** [comment]
Thanks! I already managed to get my hands on a log (I gave my old Buds to a good friend some time ago and lent them quickly) and unfortunately the original Buds behave differently when enabling `MSG_ID_VOICE_NOTI_STATUS`.
The setting only blocks single-tap events which would not work with the method I talked about yesterday (we could remap single-tap events at most).

That only affects the old Buds though, this feature would only be available to Buds+ (and maybe Buds Live) devices.

Also, thanks for the virtual monitor recommendation, I'll have a look later. 👍

**Comment by ThePBone** [comment]
> And also if you have mood for that (though here I am being seriously petty) - connection popup only appears on main screen - what about dual screen setups? Or even more screen setups? Though I only have two.

Popups should now be displayed on all connected screens. Here's an updated installer: 
[Setup_GalaxyBudsManager_3.1.0.1b.zip](https://github.com/ThePBone/GalaxyBudsClient/files/5435598/Setup_GalaxyBudsManager_3.1.0.1b.zip)

**Comment by ArthurWolfhound** [comment]
No comments here, and I don't know how you intended it but it shows up only on _not_ main screen - but that's kinda what I wanted, so thanks :)

image

**Comment by ThePBone** [comment]
Actually, I'm iterating over all screens to get the workspace rectangles to draw them. It displays for me on both screens, but I'll add an extra switch in case anyone is inconvenienced by this issue.

**Comment by ArthurWolfhound** [comment]
Checked on your debug notes, what app did you use to monitor all packets between PC and Buds? Cause I am actually searching for a way to intercept my Logitech Craft Packets (especially those that control the dial) because I want to learn something and develop my version of Logitech Options. They haven't unlocked even a pint of the potential that dial carries inside.

Do you have any other useful notes, like maybe some literature about serial monitoring, connection, wireless interceptions, other stuff?

**Comment by ThePBone** [comment]
I had to write my own monitoring tool using the [32feet .Net library](https://github.com/inthehand/32feet) because I was unable to find anything to monitor (BR/EDR) Bluetooth serial packets on Windows. Not even Wireshark supports Bluetooth monitoring on Windows.

I don't have any literature about it on hand, but normally you start by checking the Bluetooth services a device advertises. Windows tools for this are really hard to find and even partially broken/out-dated/discontinued, so it would probably be a bit easier to do this on a Linux machine instead. 
The easiest way to start off would probably be to write small Python scripts with the PyBluez library which is pretty high-level and easy to understand. ([like this one for example](https://github.com/ThePBone/GalaxyBuds-BatteryLevel/blob/master/buds_battery.py))
You'd start by connecting to the Service Discovery Protocol (SDP) of the device and start collecting services and their UUIDs (although this is mostly handled by BT libraries). Once you found a service that seems interesting, you take this UUID and request to open a new connection to that service/profile. And from then on you can exchange data and analyze it.

This blog post is a pretty good introduction to reversing a serial rfcomm protocol: http://travisgoodspeed.blogspot.com/2011/12/introduction-to-bluetooth-rfcomm.html

But in your case, I'd just use Logitech's official API for the keyboard: https://github.com/Logitech/logi_craft_sdk/blob/master/documentation/Craft_Crown_SDK.md
It looks like there are C#, C++, and Python bindings for it.

**Comment by ArthurWolfhound** [comment]
Thanks for hints!

About Crown SDK, yeah been there - it allows to write a plugin for a specific app to interact with, like say Premiere allows to scroll the timeline, I could implement wanted functionality in other app.

But that's just not my way - that is too low for me. I want full control but that seems like I will need to write everything from scratch starting from drivers.

**Comment by ThePBone** [comment]
>Concept: Is it possible to implement something like a service-based solution that will catch normally set functions from Buds, but treat them differently because Custom actions Mode is Active?

Update:
Nvm, the method I proposed was unable to suppress default touch events, other than play/pause from the single tap event.
I found another method using a registry hack, unfortunately, it cannot override long-press actions without altering the settings on the Buds itself.
It could only be used to remap single, double, and triple touch events with custom actions (and to disable the pause event when taking the earbuds off).

However, that method requires changing a registry key owned by the Bluetooth audio service which runs under the SYSTEM account (higher privilege than admin), so I don't know whether I can include it as a remapper into the app without offending anti-virus programs.

Nevertheless, I wrote a small wiki entry about this: <https://github.com/ThePBone/GalaxyBudsClient/wiki/5.-Tips-and-tricks#suppress-bluetooth-media-button-events-windows>

**Pull request closed without merging**
