### PR TITLE
Add Indonesian Language Translation

### PR DESCRIPTION
**Pull request by giovankabisano**
Hi! I love your project and i want to give a little contribution by adding Indonesian language translation.
I've test it and make sure that no text get overlapped by a layout :)

### CODE REVIEW

**Comment by ArthurWolfhound** [comment]
Hi! I also wrote translations for this application, please check on my response to Portuguese translation pull request because you have same problem with update available page.

Cheers!

**Comment by giovankabisano** [comment]
> Hi! I also wrote translations for this application, please check on my response to Portuguese translation pull request because you have same problem with update available page.
> 
> Cheers!

Hi dude, what seems to be the problem @ArthurWolfhound ? I still don't understand. Maybe can you please point out on what should i do?

Btw, when I create this translation, I also use `custom_language.xaml` to check whether my translation already suits the application and it's context.

**Comment by ArthurWolfhound** [comment]
image

That lower left button there...

**Comment by giovankabisano** [comment]
Oh shoot... I miss that part. Thanks for checking dude!

**Comment by giovankabisano** [comment]
Done, i've change that too long translation that results the words got covered up. (Bottom left)
 
image

**Comment by giovankabisano** [comment]
I've also recheck all of translated page using "Translator Mode". 
With that mode, I found some typos (my bad) but I've fixed that as well and found no other covered translation.

image

**Pull request merged**
