### PR TITLE
Edit package 06122020

### PR DESCRIPTION
**Pull request by ArthurWolfhound**
Hi there! Hope you're doing great in those trying times... I am currently in a quarantine hellhole - my university education was, let's say not great and with remote education it is outright pathetic. But, to business.

1. Issue templates. I don't know how do you like them and will you need to activate them manually in you repository settings, but either way I hope you'll take templates I've prepared.
2. I still haven't updated READMEs with new translators and other stuff because of point 3.
3. Repository wiki. That will be better for everybody. BUT! Unfortunately GitHub is incredibly dumb when it comes to wikis so you'll need to do some tinkering in order to copy my version...
3.1. Create a wiki with a blank Home page
3.2. Do this on your PC
> git clone https://github.com/ThePBone/GalaxyBudsClient.wiki.git
> git remote add fork https://github.com/ArthurWolfhound/GalaxyBudsClient.wiki.git
> git push -f fork master

You now should have a full copy of my wiki, and ability to update it with one command.
4. There is some minor language edits, one of which actually concerns an unexpected behavior.
- When in translator mode, if you close application before translator window, tray icon no longer does anything. It just sits there and exit command is doing nothing. But you can still close translator window with an X. So, not really a bug, just an unexpected behavior.
- When in translator mode, it seems like tray icon does not load all the strings even when Buds Model is being forced. Though this one is not really a problem, tray icon menu is not so limited, right?

5. Onto other things
- I don't know if this is a problem with my laptop or slide transitions can be made, I don't know 5% faster?
- I've checked language files and according to one of the recent issues you've reverted there is no longer ability to control multi-monitor solutions, can you maybe, drop 3.1.1.5 to releases?

I don't guarantee how long will it take for me to make readme changes and maybe other stuff for wiki, cause exams. A spectacular disaster. But I will try to hang around for a while. Maybe take a day for contributions every two weeks. Who knows. Cheers!

### CODE REVIEW

**Comment by ArthurWolfhound** [comment]
I also should have commented that you probably would be able to move full feature list to the wiki, alongside with your reverse-engineering journals, but that's up to you.

**Comment by ThePBone** [comment]
Thanks a lot!
I'll enable all issue templates, they'll probably save a lot of time and make it easier for users to fix that configuration corruption bug themselves.
Also, the wiki seems like an excellent solution compared to my cluttered README. :sweat_smile: 

> When in translator mode, if you close application before translator window, tray icon no longer does anything. It just sits there and exit command is doing nothing. But you can still close translator window with an X. 

I'm currently rewriting the whole app from scratch with a new UI toolkit for native Linux compatibility (excluding systems running proprietary Nvidia drivers, for now. Their driver segfaults when the Skia rendering engine tries to do anything complicated).
Since that toolkit has no support for tray icons, I'll have to create my own native implementation (one for Windows and one for Linux), so I'll have to redo the tray bar handling anyway.

> When in translator mode, it seems like tray icon does not load all the strings even when Buds Model is being forced. Though this one is not really a problem, tray icon menu is not so limited, right

Issues when forcing other device models are expected, sometimes it may just require a restart, and other times the unexpected model change causes undefined behavior because of some edge-cases that would never occur under normal use.
The new implementation has a specific `EventHandler<Locales>? LanguageChanged` event available, so cached strings in the C# source code can be instantly refreshed, just like XAML string resources.

**Comment by ThePBone** [comment]
> don't know if this is a problem with my laptop or slide transitions can be made, I don't know 5% faster?

Yes, sure. Currently, the new implementation removes those actually altogether. But if you and other people are still using them, I can reintroduce them.

> I've checked language files and according to one of the recent issues you've reverted there is no longer able to control multi-monitor solutions, can you maybe, drop 3.1.1.5 to releases?

Yes, I'll do that later. There are some other fixes that I had laying around and forgot about them.

**Comment by ArthurWolfhound** [comment]
About sliding animations, it's only up to you. I've only mentioned them cause I didn't use them because of slowness.

Glad to help! Will return sometimes later.

**Pull request merged**
