### PR TITLE
Use buds icon for menubar

### PR DESCRIPTION
**Pull request by sidevesh**
Show the icon of buds on the menubar,
this is to to integrate it better with system,
similar to how AirPods show up in menubar

### CODE REVIEW

**Comment by sidevesh** [comment]
these also fit better when the menubar is in light mode due to having a gray border

**Comment by sidevesh** [comment]
Screenshot 2024-02-10 at 2 08 24 PM
Here is how it looks

**Comment by sidevesh** [comment]
It still does not look very good when menubar is in light mode,
although this was an issue with the previous icon too, but even worse,
I am not sure how to set a different icon for light mode in Avalonia for macOS,
if that is possible then let me know and I will create black variants of the icons like the other macOS menubar icons as you can see in the screenshot below.
Screenshot 2024-02-10 at 2 11 33 PM

**Comment by ThePBone** [comment]
Avalonia is getting a new feature that allows for theme-aware menubar icons on macOS: https://github.com/AvaloniaUI/Avalonia/pull/14348
That way, the icon will be automatically re-colored by macOS. However, as far as I understood, only the outline of the icon would be visible.

**Comment by maxkatz6** [comment]
Not the outline. It works the same way as native macOS apps handle it. You provide a template icon with transparency, and macOS will color black or white everything that isn't transparent. In my PR there is just a bad example of an icon.

**Comment by sidevesh** [comment]
Opened #462 to track this @ThePBone @maxkatz6

**Pull request merged**
