### PR TITLE
Add a connection popup

### PR DESCRIPTION
**Pull request by githubcatw**
I added a connection popup that looks like the one the Android app has.

popup

### CODE REVIEW

**Comment by ThePBone** [comment]
Thanks for the cool contribution!

I'll merge your changes to an extra branch before finally applying them to the master, in order to modify it a little bit.

Some stuff that should/could be changed/added before merging it with master:
* I think an immersive dialog is a bit too much; it covers the whole screen and may distract the user from whatever he was working on. I'd rather turn it into a standard overlay/dialog which disappears automatically after ~5 seconds if the user doesn't click it (notification-like behavior)
* Fade animations
* Add battery percentages to it
* Update dimensions to match the other elements in the normal window

I can take a look at those things and add them. Feel free to send a PR to the `popup` branch if you want to change or add anything.

**Comment by ThePBone** [comment]
Sorry, but I've decided not to merge it.

Your code is too loosely implemented and mixed with other parts that are completely unrelated to it (e.g. the dialog is called within a menu-generation routine).
This unnecessarily complicates the code and makes it very error-prone, since it is called even though it shouldn't be. 
The stuff I pointed out above is also pretty much necessary to enable a good UI and user experience. Fixing all of that would require me to rewrite and discard ALL of your code, which defeats the point of a pull request.

If you can fulfill all requirements stated above, you can submit another PR.

**Comment by githubcatw** [comment]
Thanks, I'll fix the code and submit another PR.

**Comment by githubcatw** [comment]
Sorry for asking, but is there a handler for when the buds connect to the PC? I tried adding the popup code to `InstanceOnStatusUpdate` but the popup only showed up whenever I disconnected the buds by closing the case (funnily enough).

**Pull request merged**
